import streamlit as st
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import io

st.set_page_config(page_title="Compare Models", layout="wide")
st.title("Compare Models")

if "model_results" not in st.session_state or not st.session_state["model_results"]:
    st.info("No trained models yet. Go to the Train Model page and train at least one model.")
    st.stop()

results = st.session_state["model_results"]

# ── Metrics table ─────────────────────────────────────────────────────────────
st.subheader("Metrics Comparison")
rows = []
for r in results:
    row = {"Model": r["name"], "Task": r["task"]}
    row.update(r["metrics"])
    rows.append(row)

metrics_df = pd.DataFrame(rows)
st.dataframe(
    metrics_df.style.highlight_max(
        axis=0,
        subset=[c for c in metrics_df.columns if c not in ("Model","Task")],
        color="#d4edda"
    ),
    use_container_width=True
)

# ── Bar chart ─────────────────────────────────────────────────────────────────
st.subheader("Visual Comparison")
metric_cols = [c for c in metrics_df.columns if c not in ("Model","Task")]
if metric_cols:
    chosen_metric = st.selectbox("Select metric to compare", metric_cols)
    fig, ax = plt.subplots(figsize=(max(6, len(results)*1.5), 4))
    colors = plt.cm.Blues(np.linspace(0.4, 0.9, len(results)))
    bars = ax.bar(metrics_df["Model"], metrics_df[chosen_metric], color=colors)
    ax.set_title(f"{chosen_metric} by Model")
    ax.set_ylabel(chosen_metric)
    ax.tick_params(axis="x", rotation=30)
    for bar in bars:
        h = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2, h, f"{h:.4f}",
                ha="center", va="bottom", fontsize=9)
    st.pyplot(fig, use_container_width=True)
    plt.close()

# ── Best model ────────────────────────────────────────────────────────────────
if metric_cols:
    best_idx = metrics_df[chosen_metric].idxmax()
    st.success(
        f"Best model on {chosen_metric}: "
        f"{metrics_df.loc[best_idx, 'Model']} "
        f"({metrics_df.loc[best_idx, chosen_metric]:.4f})"
    )

# ── Manage models ─────────────────────────────────────────────────────────────
st.divider()
st.subheader("Manage Models")
del_name = st.selectbox("Remove model from comparison", ["(none)"] + [r["name"] for r in results])
if st.button("Remove selected model") and del_name != "(none)":
    st.session_state["model_results"] = [r for r in results if r["name"] != del_name]
    st.success(f"Removed {del_name}.")
    st.rerun()

# ── Export HTML report ────────────────────────────────────────────────────────
st.divider()
st.subheader("Export Report")

if st.button("Generate HTML Report"):
    html_rows = "".join(
        f"<tr><td>{r['Model']}</td><td>{r['Task']}</td>"
        + "".join(f"<td>{v:.4f}</td>" for v in r["metrics"].values())
        + "</tr>"
        for r in rows
    )
    metric_headers = "".join(f"<th>{c}</th>" for c in metric_cols)

    html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>ML Studio - Model Comparison Report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 40px; color: #333; }}
    h1 {{ color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }}
    p {{ color: #555; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
    th {{ background: #1a1a2e; color: white; padding: 10px 14px; text-align: left; }}
    td {{ padding: 8px 14px; border-bottom: 1px solid #ddd; }}
    tr:hover {{ background: #f0f4ff; }}
    .footer {{ margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 12px; }}
  </style>
</head>
<body>
  <h1>ML Studio - Model Comparison Report</h1>
  <p>Total models evaluated: <strong>{len(results)}</strong></p>
  <table>
    <thead><tr><th>Model</th><th>Task</th>{metric_headers}</tr></thead>
    <tbody>{html_rows}</tbody>
  </table>
  <div class="footer">Generated by ML Studio</div>
</body>
</html>"""

    st.download_button(
        "Download HTML Report",
        html.encode(),
        "ml_studio_report.html",
        "text/html"
    )

# ── Export predictions ────────────────────────────────────────────────────────
if "last_model" in st.session_state and "df" in st.session_state:
    last = st.session_state["last_model"]
    if last["task"] in ("Classification", "Regression"):
        if st.button("Export predictions from last trained model"):
            try:
                from sklearn.preprocessing import LabelEncoder
                df = st.session_state["df"].copy()
                X = df[last["feature_cols"]].copy()
                for c in X.select_dtypes(include=["object","category"]).columns:
                    X[c] = LabelEncoder().fit_transform(X[c].astype(str))
                X = X.fillna(X.median(numeric_only=True))
                preds = last["model"].predict(X)
                out_df = df.copy()
                out_df["prediction"] = preds
                csv = out_df.to_csv(index=False).encode()
                st.download_button("Download predictions CSV", csv, "predictions.csv", "text/csv")
            except Exception as e:
                st.error(f"Could not generate predictions: {e}")
